// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://punnnzwzfmrzqqyfwcfb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB1bm5uend6Zm1yenFxeWZ3Y2ZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3Nzg4ODUsImV4cCI6MjA3MDM1NDg4NX0.y-LfbQXm81ZaWDHnsqAim5QjZsPuKqx5-1CiQJwE31U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});